services:
  sky-trading-server:
    image: nodejs
    container_name: sky-trading-server
    restart: always
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - sky-trading-networks
networks:
  sky-trading-network:
    driver: bridge
    name: sky-trading-network

volumes:
  node_modules:


