name: CI & CD Sky-Trading-API

on:
  push:
    branches: dev-setup
  pull_request:
    branches: dev-setup

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout source code
      - name: Checkout source
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 3: Run tests
      - name: Run tests
        run: npm run test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout source code
      - name: Checkout source
        uses: actions/checkout@v3

      # Step 2: SSH into the server and build the Docker image locally
      - name: Build and deploy on server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/sky-trading-api
            sudo git pull
            sudo docker compose up -d --build   
          # debug: true
